server:
  port: 8000

spring:

  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_IP:localhost:8848}
    gateway:
      # 全局跨域配置
      globalcors:
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        # 指定匹配所有路由（所有请求路径）的跨域配置
        corsConfigurations:
          '[/**]':
            # 允许的请求来源，可以根据需要调整为具体的地址或使用 "*" 表示所有来源
            allowedOrigins: "http://localhost:5173"
            # 允许携带凭证（如 Cookies）
            allowCredentials: true
            # 允许的请求头
            allowedHeaders: "*"
            # 允许的 HTTP 请求方法
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      # 动态路由配置
      discovery:
        locator:
          enabled: true

      routes:
        - id: auth-service-route
          uri: lb://im-auth-service
          predicates:
            - Path=/auth/**

        - id: main-service-route
          uri: lb://im-main-service
          predicates:
            - Path=/main/**

        - id: file-service-route
          uri: lb://im-file-service
          predicates:
            - Path=/file/**

